PLAYER_MAX_MANA_AND_HEALTH_VALUE = 100
PLAYER_MIN_MANA_AND_HEALTH_VALUE = 0
PLAYER_ATTACK_BY_WEAPON_STRING = 'weapon'
PLAYER_ATTACK_BY_SPELL_STRING = 'spell'
ENEMY_MIN_MANA_AND_HEALTH_WHEN_INITIALISING = 50
ENEMY_MAX_MANA_AND_HEALTH_WHEN_INITIALISING = 100
ENEMY_MIN_DAMAGE_WHEN_INITIALISING = 10
ENEMY_MAX_DAMAGE_WHEN_INITIALISING = 50
